/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.usuario.master.persistence;

import co.edu.uniandes.csw.Arquidalgos.cita.logic.dto.CitaDTO;
import co.edu.uniandes.csw.Arquidalgos.cita.persistence.converter.CitaConverter;
import co.edu.uniandes.csw.Arquidalgos.turno.logic.dto.TurnoDTO;
import co.edu.uniandes.csw.Arquidalgos.turno.persistence.converter.TurnoConverter;
import co.edu.uniandes.csw.Arquidalgos.usuario.logic.dto.UsuarioDTO;
import javax.ejb.Stateless;

import co.edu.uniandes.csw.Arquidalgos.usuario.master.persistence.api.IUsuarioMasterPersistence;
import co.edu.uniandes.csw.Arquidalgos.usuario.master.persistence.entity.UsuariocitasUsEntity;
import co.edu.uniandes.csw.Arquidalgos.usuario.master.persistence.entity.UsuarioturnoUsuarioEntity;
import java.util.List;
import javax.ejb.LocalBean;
import javax.enterprise.inject.Default;
import javax.persistence.Query;
import utilidadesHTV.ConstantesYMetodos;
import utilidadesHTV.Tiempo;

@Default
@Stateless 
@LocalBean
public class UsuarioMasterPersistence extends _UsuarioMasterPersistence  implements IUsuarioMasterPersistence {

    public CitaDTO getCitaUsuarioHoy(Long usuarioId) {
       
        Query q = entityManager.createNamedQuery("UsuariocitasUsEntity.getByMasterId");
        q.setParameter("usuarioId",usuarioId);
        List<UsuariocitasUsEntity> qResult =  q.getResultList();
        for (UsuariocitasUsEntity entity : qResult) {
            
            if ( ConstantesYMetodos.citasMismoDia(entity.getCitasUsIdEntity().getFechaCita(),Tiempo.getCurrentDate())){
                if(entity.getCitasUsIdEntity()==null){
                    entityManager.refresh(entity);
                }
                return CitaConverter.entity2PersistenceDTO(entity.getCitasUsIdEntity());
                
            }
        }
        return null;
    }
    public UsuarioDTO getUsuarioCitaHoy(Long citaId) {
       
        Query q = entityManager.createNamedQuery("UsuariocitasUsEntity.getByCitaId");
        q.setParameter("citasUsId",citaId);
        List<UsuariocitasUsEntity> qResult =  q.getResultList();
        for (UsuariocitasUsEntity entity : qResult) {
            
            if ( ConstantesYMetodos.citasMismoDia(entity.getCitasUsIdEntity().getFechaCita(),Tiempo.getCurrentDate())){
                if(usuarioPersistence.getUsuario(entity.getUsuarioId())==null){
                    entityManager.refresh(entity);
                }
                return usuarioPersistence.getUsuario(entity.getUsuarioId());
            }
        }
        return null;
    }
    
    
    public TurnoDTO getTurnoUsuarioHoy(Long usuarioId) {
        
        Query q = entityManager.createNamedQuery("UsuarioturnoUsuarioEntity.getByMasterId");
        q.setParameter("usuarioId",usuarioId);
        List<UsuarioturnoUsuarioEntity> qResult =  q.getResultList();
        for (UsuarioturnoUsuarioEntity entity : qResult) { 
            
            if ( ConstantesYMetodos.citasMismoDia(entity.getTurnoUsuarioIdEntity().getFechaTurno(),Tiempo.getCurrentDate())){
                if(entity.getTurnoUsuarioIdEntity()==null){
                    entityManager.refresh(entity);
                }
                return TurnoConverter.entity2PersistenceDTO(entity.getTurnoUsuarioIdEntity());
            }
        }
        return null;
    }
    
     public UsuarioDTO getUsuarioTurnoHoy(Long turnoId) {
        
        Query q = entityManager.createNamedQuery("UsuarioturnoUsuarioEntity.getByTurnoId");
        q.setParameter("turnoUsuarioId",turnoId);
        List<UsuarioturnoUsuarioEntity> qResult =  q.getResultList();
        for (UsuarioturnoUsuarioEntity entity : qResult) { 
            
            if ( ConstantesYMetodos.citasMismoDia(entity.getTurnoUsuarioIdEntity().getFechaTurno(),Tiempo.getCurrentDate())){
                if(entity.getTurnoUsuarioIdEntity()==null){
                    entityManager.refresh(entity);
                }
            
                return usuarioPersistence.getUsuario(entity.getUsuarioId());
            }
        }
        return null;
    }
}