/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.turno.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.Arquidalgos.turno.logic.dto.TurnoDTO;
import co.edu.uniandes.csw.Arquidalgos.turno.persistence.entity.TurnoEntity;

public abstract class _TurnoConverter {

	public static TurnoDTO entity2PersistenceDTO(TurnoEntity entity){
		if (entity != null) {
			TurnoDTO dto = new TurnoDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setTurno(entity.getTurno());
					dto.setSedeturnoId(entity.getSedeturnoId());
                                        dto.setFechaTurno(entity.getFechaTurno());
                                        dto.setHoraFinal(entity.getHoraFinal());
                                        dto.setHoraInicio(entity.getHoraInicio());
                                        System.out.println("TurnoConventer entity-dto Entity: ID "
                                                +entity.getId()+" Fecha "+entity.getFechaTurno()+ " inicio "+
                                                entity.getHoraInicio()+ " final "+ entity.getHoraFinal()+
                                                " sede "+entity.getSedeturnoId());
                                        System.out.println("TurnoConventer entity-dto DTO: ID "
                                                +dto.getId()+" Fecha "+dto.getFechaTurno()+ " inicio "+
                                                dto.getHoraInicio()+ " final "+ dto.getHoraFinal()+
                                                " sede "+dto.getSedeturnoId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static TurnoEntity persistenceDTO2Entity(TurnoDTO dto){
		if(dto!=null){
			TurnoEntity entity=new TurnoEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setTurno(dto.getTurno());
			
					entity.setSedeturnoId(dto.getSedeturnoId());
                                        
                                        entity.setFechaTurno(dto.getFechaTurno());
                                        entity.setHoraFinal(dto.getHoraFinal());
                                        entity.setHoraInicio(dto.getHoraInicio());
                                        System.out.println("TurnoConventer dto-entity Entity: ID "
                                                +entity.getId()+" Fecha "+entity.getFechaTurno()+ " inicio "+
                                                entity.getHoraInicio()+ " final "+ entity.getHoraFinal()+
                                                " sede "+entity.getSedeturnoId());
                                        System.out.println("TurnoConventer dto-entity DTO: ID "
                                                +dto.getId()+" Fecha "+dto.getFechaTurno()+ " inicio "+
                                                dto.getHoraInicio()+ " final "+ dto.getHoraFinal()+
                                                " sede "+dto.getSedeturnoId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<TurnoDTO> entity2PersistenceDTOList(List<TurnoEntity> entities){
		List<TurnoDTO> dtos=new ArrayList<TurnoDTO>();
		for(TurnoEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<TurnoEntity> persistenceDTO2EntityList(List<TurnoDTO> dtos){
		List<TurnoEntity> entities=new ArrayList<TurnoEntity>();
		for(TurnoDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}