/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.haztuvuelta.master.persistence.entity;

import co.edu.uniandes.csw.Arquidalgos.usuario.persistence.entity.UsuarioEntity;
import co.edu.uniandes.csw.Arquidalgos.haztuvuelta.persistence.entity.HazTuVueltaEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(HazTuVueltausuariosHtvEntityId.class)
@NamedQueries({
    @NamedQuery(name = "HazTuVueltausuariosHtvEntity.getByMasterId", query = "SELECT  u FROM HazTuVueltausuariosHtvEntity u WHERE u.hazTuVueltaId=:hazTuVueltaId"),
    @NamedQuery(name = "HazTuVueltausuariosHtvEntity.deleteHazTuVueltausuariosHtvEntity", query = "DELETE FROM HazTuVueltausuariosHtvEntity u WHERE u.hazTuVueltaId=:hazTuVueltaId and  u.usuariosHtvId=:usuariosHtvId")
})
public class HazTuVueltausuariosHtvEntity implements Serializable {

    @Id
    @Column(name = "hazTuVueltaId")
    private Long hazTuVueltaId;
    @Id
    @Column(name = "usuariosHtvId")
    private Long usuariosHtvId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "hazTuVueltaId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity hazTuVueltaIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "usuariosHtvId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity usuariosHtvIdEntity; 

    public HazTuVueltausuariosHtvEntity() {
    }

    public HazTuVueltausuariosHtvEntity(Long hazTuVueltaId, Long usuariosHtvId) {
        this.hazTuVueltaId =hazTuVueltaId;
        this.usuariosHtvId = usuariosHtvId;
    }

    public Long getHazTuVueltaId() {
        return hazTuVueltaId;
    }

    public void setHazTuVueltaId(Long hazTuVueltaId) {
        this.hazTuVueltaId = hazTuVueltaId;
    }

    public Long getUsuariosHtvId() {
        return usuariosHtvId;
    }

    public void setUsuariosHtvId(Long usuariosHtvId) {
        this.usuariosHtvId = usuariosHtvId;
    }

    public UsuarioEntity getHazTuVueltaIdEntity() {
        return hazTuVueltaIdEntity;
    }

    public void setHazTuVueltaIdEntity(UsuarioEntity hazTuVueltaIdEntity) {
        this.hazTuVueltaIdEntity = hazTuVueltaIdEntity;
    }

    public UsuarioEntity getUsuariosHtvIdEntity() {
        return usuariosHtvIdEntity;
    }

    public void setUsuariosHtvIdEntity(UsuarioEntity usuariosHtvIdEntity) {
        this.usuariosHtvIdEntity = usuariosHtvIdEntity;
    }

}
