/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.haztuvuelta.master.persistence.entity;

import co.edu.uniandes.csw.Arquidalgos.entidad.persistence.entity.EntidadEntity;
import co.edu.uniandes.csw.Arquidalgos.haztuvuelta.persistence.entity.HazTuVueltaEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(HazTuVueltatiendaOPEntityId.class)
@NamedQueries({
    @NamedQuery(name = "HazTuVueltatiendaOPEntity.getByMasterId", query = "SELECT  u FROM HazTuVueltatiendaOPEntity u WHERE u.hazTuVueltaId=:hazTuVueltaId"),
    @NamedQuery(name = "HazTuVueltatiendaOPEntity.deleteHazTuVueltatiendaOPEntity", query = "DELETE FROM HazTuVueltatiendaOPEntity u WHERE u.hazTuVueltaId=:hazTuVueltaId and  u.tiendaOPId=:tiendaOPId")
})
public class HazTuVueltatiendaOPEntity implements Serializable {

    @Id
    @Column(name = "hazTuVueltaId")
    private Long hazTuVueltaId;
    @Id
    @Column(name = "tiendaOPId")
    private Long tiendaOPId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "hazTuVueltaId", referencedColumnName = "id")
    @JoinFetch
    private EntidadEntity hazTuVueltaIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "tiendaOPId", referencedColumnName = "id")
    @JoinFetch
    private EntidadEntity tiendaOPIdEntity; 

    public HazTuVueltatiendaOPEntity() {
    }

    public HazTuVueltatiendaOPEntity(Long hazTuVueltaId, Long tiendaOPId) {
        this.hazTuVueltaId =hazTuVueltaId;
        this.tiendaOPId = tiendaOPId;
    }

    public Long getHazTuVueltaId() {
        return hazTuVueltaId;
    }

    public void setHazTuVueltaId(Long hazTuVueltaId) {
        this.hazTuVueltaId = hazTuVueltaId;
    }

    public Long getTiendaOPId() {
        return tiendaOPId;
    }

    public void setTiendaOPId(Long tiendaOPId) {
        this.tiendaOPId = tiendaOPId;
    }

    public EntidadEntity getHazTuVueltaIdEntity() {
        return hazTuVueltaIdEntity;
    }

    public void setHazTuVueltaIdEntity(EntidadEntity hazTuVueltaIdEntity) {
        this.hazTuVueltaIdEntity = hazTuVueltaIdEntity;
    }

    public EntidadEntity getTiendaOPIdEntity() {
        return tiendaOPIdEntity;
    }

    public void setTiendaOPIdEntity(EntidadEntity tiendaOPIdEntity) {
        this.tiendaOPIdEntity = tiendaOPIdEntity;
    }

}
