/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.usuario.master.logic.dto;

import co.edu.uniandes.csw.Arquidalgos.cita.logic.dto.CitaDTO;
import co.edu.uniandes.csw.Arquidalgos.turno.logic.dto.TurnoDTO;
import co.edu.uniandes.csw.Arquidalgos.usuario.logic.dto.UsuarioDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _UsuarioMasterDTO {

 
    protected UsuarioDTO usuarioEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public UsuarioDTO getUsuarioEntity() {
        return usuarioEntity;
    }

    public void setUsuarioEntity(UsuarioDTO usuarioEntity) {
        this.usuarioEntity = usuarioEntity;
    }
    
    public List<CitaDTO> createcitasUs;
    public List<CitaDTO> updatecitasUs;
    public List<CitaDTO> deletecitasUs;
    public List<CitaDTO> listcitasUs;	
    public List<TurnoDTO> createturnoUsuario;
    public List<TurnoDTO> updateturnoUsuario;
    public List<TurnoDTO> deleteturnoUsuario;
    public List<TurnoDTO> listturnoUsuario;	
	
	
	
    public List<CitaDTO> getCreatecitasUs(){ return createcitasUs; };
    public void setCreatecitasUs(List<CitaDTO> createcitasUs){ this.createcitasUs=createcitasUs; };
    public List<CitaDTO> getUpdatecitasUs(){ return updatecitasUs; };
    public void setUpdatecitasUs(List<CitaDTO> updatecitasUs){ this.updatecitasUs=updatecitasUs; };
    public List<CitaDTO> getDeletecitasUs(){ return deletecitasUs; };
    public void setDeletecitasUs(List<CitaDTO> deletecitasUs){ this.deletecitasUs=deletecitasUs; };
    public List<CitaDTO> getListcitasUs(){ return listcitasUs; };
    public void setListcitasUs(List<CitaDTO> listcitasUs){ this.listcitasUs=listcitasUs; };	
    public List<TurnoDTO> getCreateturnoUsuario(){ return createturnoUsuario; };
    public void setCreateturnoUsuario(List<TurnoDTO> createturnoUsuario){ this.createturnoUsuario=createturnoUsuario; };
    public List<TurnoDTO> getUpdateturnoUsuario(){ return updateturnoUsuario; };
    public void setUpdateturnoUsuario(List<TurnoDTO> updateturnoUsuario){ this.updateturnoUsuario=updateturnoUsuario; };
    public List<TurnoDTO> getDeleteturnoUsuario(){ return deleteturnoUsuario; };
    public void setDeleteturnoUsuario(List<TurnoDTO> deleteturnoUsuario){ this.deleteturnoUsuario=deleteturnoUsuario; };
    public List<TurnoDTO> getListturnoUsuario(){ return listturnoUsuario; };
    public void setListturnoUsuario(List<TurnoDTO> listturnoUsuario){ this.listturnoUsuario=listturnoUsuario; };	
	
	
}

