/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.haztuvuelta.master.persistence;
import co.edu.uniandes.csw.Arquidalgos.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.Arquidalgos.haztuvuelta.master.persistence.entity.HazTuVueltausuariosHtvEntity;
import co.edu.uniandes.csw.Arquidalgos.usuario.persistence.converter.UsuarioConverter;
import co.edu.uniandes.csw.Arquidalgos.entidad.logic.dto.EntidadDTO;
import co.edu.uniandes.csw.Arquidalgos.haztuvuelta.master.persistence.entity.HazTuVueltatiendaOPEntity;
import co.edu.uniandes.csw.Arquidalgos.entidad.persistence.converter.EntidadConverter;
import co.edu.uniandes.csw.Arquidalgos.haztuvuelta.logic.dto.HazTuVueltaDTO;
import co.edu.uniandes.csw.Arquidalgos.haztuvuelta.master.logic.dto.HazTuVueltaMasterDTO;
import co.edu.uniandes.csw.Arquidalgos.haztuvuelta.master.persistence.api._IHazTuVueltaMasterPersistence;
import co.edu.uniandes.csw.Arquidalgos.haztuvuelta.persistence.api.IHazTuVueltaPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _HazTuVueltaMasterPersistence implements _IHazTuVueltaMasterPersistence {

  	@PersistenceContext(unitName="HazTuVueltaPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IHazTuVueltaPersistence haztuvueltaPersistence;  

    public HazTuVueltaMasterDTO getHazTuVuelta(Long haztuvueltaId) {
        HazTuVueltaMasterDTO haztuvueltaMasterDTO = new HazTuVueltaMasterDTO();
        HazTuVueltaDTO haztuvuelta = haztuvueltaPersistence.getHazTuVuelta(haztuvueltaId);
        haztuvueltaMasterDTO.setHazTuVueltaEntity(haztuvuelta);
        haztuvueltaMasterDTO.setListusuariosHtv(getHazTuVueltausuariosHtvEntityList(haztuvueltaId));
        haztuvueltaMasterDTO.setListtiendaOP(getHazTuVueltatiendaOPEntityList(haztuvueltaId));
        return haztuvueltaMasterDTO;
    }

    public HazTuVueltausuariosHtvEntity createHazTuVueltausuariosHtvEntity(HazTuVueltausuariosHtvEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteHazTuVueltausuariosHtvEntity(Long hazTuVueltaId, Long usuariosHtvId) {
        Query q = entityManager.createNamedQuery("HazTuVueltausuariosHtvEntity.deleteHazTuVueltausuariosHtvEntity");
        q.setParameter("hazTuVueltaId", hazTuVueltaId);
        q.setParameter("usuariosHtvId", usuariosHtvId);
        q.executeUpdate();
    }

    public List<UsuarioDTO> getHazTuVueltausuariosHtvEntityList(Long hazTuVueltaId) {
        ArrayList<UsuarioDTO> resp = new ArrayList<UsuarioDTO>();
        Query q = entityManager.createNamedQuery("HazTuVueltausuariosHtvEntity.getByMasterId");
        q.setParameter("hazTuVueltaId",hazTuVueltaId);
        List<HazTuVueltausuariosHtvEntity> qResult =  q.getResultList();
        for (HazTuVueltausuariosHtvEntity entity : qResult) { 
            if(entity.getUsuariosHtvIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(UsuarioConverter.entity2PersistenceDTO(entity.getUsuariosHtvIdEntity()));
        }
        return resp;
    }
    public HazTuVueltatiendaOPEntity createHazTuVueltatiendaOPEntity(HazTuVueltatiendaOPEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteHazTuVueltatiendaOPEntity(Long hazTuVueltaId, Long tiendaOPId) {
        Query q = entityManager.createNamedQuery("HazTuVueltatiendaOPEntity.deleteHazTuVueltatiendaOPEntity");
        q.setParameter("hazTuVueltaId", hazTuVueltaId);
        q.setParameter("tiendaOPId", tiendaOPId);
        q.executeUpdate();
    }

    public List<EntidadDTO> getHazTuVueltatiendaOPEntityList(Long hazTuVueltaId) {
        ArrayList<EntidadDTO> resp = new ArrayList<EntidadDTO>();
        Query q = entityManager.createNamedQuery("HazTuVueltatiendaOPEntity.getByMasterId");
        q.setParameter("hazTuVueltaId",hazTuVueltaId);
        List<HazTuVueltatiendaOPEntity> qResult =  q.getResultList();
        for (HazTuVueltatiendaOPEntity entity : qResult) { 
            if(entity.getTiendaOPIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(EntidadConverter.entity2PersistenceDTO(entity.getTiendaOPIdEntity()));
        }
        return resp;
    }

}
