/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos
 
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================
 
 
 Source generated by CrudMaker version 1.0.0.201408112050
 
 */
define(['controller/_entidadController', 'delegate/entidadDelegate', 'lib/gmaps'], function () {
    App.Controller.EntidadController = App.Controller._EntidadController.extend({
        postInit: function (options) {
            var self = this;
            Backbone.on(this.componentId + '-entidad-verSedes', function (params) {
                self.verSedes();
            });
            Backbone.on(this.componentId + '-reservar', function (params) {
                self.redirectFrame('usuario.html');
            });
            Backbone.on(this.componentId + '-hideMap', function (params) {
                self.hideMap();
            });
            this.initMap();
            this.bool = false;
            if (this.isMobile())
            {
                document.getElementById("map").style.width = '100%';
            }
            this.listTemplate = _.template($('#entidadList').html());
        },
        hideMap: function () {
            console.log('Hide Map');
            var elem = document.getElementById("map");
            if (this.bool)
            {
                elem.style.display = 'block';

            }
            else
            {
                elem.style.display = 'none';
            }
            this.bool = !this.bool;


        },
        isMobile: function () {

            return (
                    (navigator.userAgent.match(/Android/i)) ||
                    (navigator.userAgent.match(/webOS/i)) ||
                    (navigator.userAgent.match(/iPhone/i)) ||
                    (navigator.userAgent.match(/iPod/i)) ||
                    (navigator.userAgent.match(/iPad/i)) ||
                    (navigator.userAgent.match(/BlackBerry/))
                    );
        },
        initMap: function () {


            //Variables-----------------------------------
            //Colores Marcadores
            var marcadorVerde = 'http://library.csun.edu/images/google_maps/marker-green.png';
            var marcadorRojo = 'http://inthespace.net/graphics/icon_google_maps2.png';
            var marcadorAmarillo = 'http://static.batchgeo.com/images/icons/yellow_shadow_Marker.png';
            var coloresMarcadores = [marcadorVerde, marcadorAmarillo, marcadorRojo];

            //Lista tramites
            var lisaTramites;

            //Lista sucursares
            var sucursales = [
                {"nombre": "SIM Cedritos", "lat": 4.7299483948472725, "lng": -74.04592265136054, "estado": 0, "entidad": 0, "dire": "Calle 147 #19-66 L31", "turnoAtencion": 20, "turnoPedido": 25},
                {"nombre": "SIM Autopista 106", "lat": 4.694117579050114, "lng": -74.05666892177871, "estado": 1, "entidad": 0, "dire": "Autopista Norte #106-25/ Piso 2", "turnoAtencion": 10, "turnoPedido": 30},
                {"nombre": "SIM Nizza", "lat": 4.708157148841132, "lng": -74.07222036964706, "estado": 2, "entidad": 0, "dire": "Transversal 60 #124-20 Int. 5", "turnoAtencion": 1, "turnoPedido": 50},
                {"nombre": "SIM Siete de Agosto", "lat": 4.658609066756216, "lng": -74.0692739630442, "estado": 2, "entidad": 0, "dire": "Calle 68 #23-27", "turnoAtencion": 33, "turnoPedido": 34},
                {"nombre": "SIM Chapinero", "lat": 4.645954660919973, "lng": -74.06414423830321, "estado": 0, "entidad": 0, "dire": "Calle 59 #13-97", "turnoAtencion": 15, "turnoPedido": 18},
                {"nombre": "SIM Galerías", "lat": 4.640811028448222, "lng": -74.07519292778781, "estado": 1, "entidad": 0, "dire": "Calle 52 #25-35", "turnoAtencion": 80, "turnoPedido": 100},
                {"nombre": "SIM San Diego", "lat": 4.612054519536214, "lng": -74.0695636416178, "estado": 2, "entidad": 0, "dire": "Carrera 7 #26-16 L5", "turnoAtencion": 2, "turnoPedido": 5},
                {"nombre": "SIM Terminal", "lat": 4.65322291854579, "lng": -74.11504854209235, "estado": 1, "entidad": 0, "dire": "Diagonal 23 #69-60 Módulo 1 (amarillo) L122", "turnoAtencion": 2, "turnoPedido": 20},
                {"nombre": "SIM Ricaurte", "lat": 4.611026548823848, "lng": -74.0885369176369, "estado": 0, "entidad": 0, "dire": "Calle 13 #26-66 y/o 25-88 Esquina", "turnoAtencion": 43, "turnoPedido": 50},
                {"nombre": "SIM Restrepo", "lat": 4.583770747387098, "lng": -74.10166230745128, "estado": 2, "entidad": 0, "dire": "Carrera 17 #19A-32 Sur", "turnoAtencion": 65, "turnoPedido": 110},
                {"nombre": "SIM Sur", "lat": 4.6144392989245215, "lng": -74.13515169865897, "estado": 0, "entidad": 0, "dire": "Carrera 69 Bis #28-21 Sur", "turnoAtencion": 71, "turnoPedido": 83},
                {"nombre": "SIM Sevillana", "lat": 4.591812981502772, "lng": -74.14576318807414, "estado": 1, "entidad": 0, "dire": "Carrera 57 #45A-08 Sur Int. 1 Centro Automotriz-La Sevillana", "turnoAtencion": 3, "turnoPedido": 22}
            ]

            //Mapa
            var map = new GMaps({
                div: '#map',
                lat: 4.657556435256028,
                lng: -74.06511385686214,
                zoom: 11,
                click: function (e) {

                    alert(map.getCenter())
                },
                dragend: function (e) {
                    alert('drag')
                }
            });

            //Marcadores
            //Inicializar marcadores
            var marcadores = [];
            for (var i = 0; i < sucursales.length; i++)
            {
                var marker1 = map.createMarker({
                    lat: sucursales[i].lat,
                    lng: sucursales[i].lng,
                    title: "" + i,
                    icon: "",
                    infoWindow: {
                        content: '<p>' + sucursales[i].nombre + '</p>'
                    },
                    click: function (e) {
                        var marcadorActual = parseInt(this.getTitle())
                        $('.infoSucursal').empty()
                        $('.turno').empty()
                        $('.infoEspera').empty()
                        $('.infoSucursal').append('<p>' + sucursales[marcadorActual].nombre + '</p>')
                        $('.infoSucursal').append('<p>' + sucursales[marcadorActual].dire + '</p>')
                        $('.turno').append('<p>' + sucursales[marcadorActual].turnoAtencion + '</p>')
                        $('.infoEspera').append('<p>Espera estimada de:</p>')
                        $('.infoEspera').append('<p style="font-size:30px">' + calcularTiempoEsperaSucursal(marcadorActual) + ' minutos</p>')
                        $('.infoEspera').append('<button class="btbPedirTurno">Pedir Turno</button>')
                    }
                });
                marcadores[marcadores.length] = marker1;
                //alert(sucursales[0].entidad);
            }

            var entidadActual = parseInt($('.selectTramites').val());
            mostrarMarcadoresEntidad(entidadActual);

            //Mostrar marcadores
            $('.selectTramites').change(function () {
                var entidadActual = parseInt($('.selectTramites').val());
                mostrarMarcadoresEntidad(entidadActual);
            });

            function calcularTiempoEsperaSucursal(iMarcador) {
                return tiempoEspera = parseInt((sucursales[iMarcador].turnoPedido - sucursales[iMarcador].turnoAtencion) * 5);//5 minutos por turno
            }
            ;

            function calcularEstadoSucursal(iMarcador) {
                var tiempo = calcularTiempoEsperaSucursal(iMarcador);
                if (tiempo < 10)
                {
                    return 0;
                }
                else if (tiempo < 20)
                {
                    return 1;
                }
                else
                {
                    return 2;
                }
            }
            ;

            function mostrarMarcadoresEntidad(iEntidad)
            {
                map.removeMarkers();
                for (var i = 0; i < marcadores.length; i++)
                {
                    if (sucursales[i].entidad == iEntidad)
                    {
                        var estado = calcularEstadoSucursal(i);
                        marcadores[i].icon = coloresMarcadores[estado];
                        map.addMarker(marcadores[i]);
                    }
                }
            }
            ;




        },
        verSedes: function () {
            var self = this;
            this.$el.slideUp("fast", function () {
                self.$el.html(self.listTemplate({entidads: self.entidadModelList.models, componentId: self.componentId, showEdit: false, showDelete: true}));
                self.$el.slideDown("fast");
            });
        },
        redirectFrame: function (url) {
            location.href = 'usuario.html';
        }
    });
    return App.Controller.EntidadController;
}); 