/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.sede.logic.api;

import co.edu.uniandes.csw.Arquidalgos.cita.logic.dto.CitaDTO;
import co.edu.uniandes.csw.Arquidalgos.turno.logic.dto.TurnoDTO;
import java.util.Date;
import java.util.List;

public interface ISedeLogicService extends _ISedeLogicService {

    
    public String aumentarTurno();
    
    public String turnoActual();
    
    public Integer asignarSiguienteTurno(Long idSede, String correo) throws Exception;
    
    public Integer atenderTurno(Long idSede);
    
    public Integer darUltimoTurnoAsignado(Long idSede);
    
    public Date darUltimoInicioDeCita(Long idSede);
    
    public Integer darUltimoTurnoAtendido(Long idSede);
    
    public String darHoraAproximadaAtencion(String correo)throws Exception;
    
    public String reservarCita(CitaDTO nuevaCita)throws Exception;

    public Integer darNumeroTurnosNoAtendidosSede ( Long idSede);
   
    public void cancelarTurnoOCita( String correo);
    
    public Integer posicionCita ( String correo);
    
    public List<TurnoDTO> darTurnosNoAtendidosSede(Long idSede);
    
    public void startThread();
    
    public Date darHoraActual();
}
