/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.cita.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.Arquidalgos.cita.logic.dto.CitaDTO;
import co.edu.uniandes.csw.Arquidalgos.cita.persistence.api._ICitaPersistence;
import co.edu.uniandes.csw.Arquidalgos.cita.persistence.converter.CitaConverter;
import co.edu.uniandes.csw.Arquidalgos.cita.persistence.entity.CitaEntity;

public abstract class _CitaPersistence implements _ICitaPersistence {

  	@PersistenceContext(unitName="HazTuVueltaPU")
 
	protected EntityManager entityManager;
	
	public CitaDTO createCita(CitaDTO cita) {
		CitaEntity entity=CitaConverter.persistenceDTO2Entity(cita);
		entityManager.persist(entity);
		return CitaConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<CitaDTO> getCitas() {
		Query q = entityManager.createQuery("select u from CitaEntity u");
		return CitaConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public CitaDTO getCita(Long id) {
		return CitaConverter.entity2PersistenceDTO(entityManager.find(CitaEntity.class, id));
	}

	public void deleteCita(Long id) {
		CitaEntity entity=entityManager.find(CitaEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateCita(CitaDTO detail) {
		CitaEntity entity=entityManager.merge(CitaConverter.persistenceDTO2Entity(detail));
		CitaConverter.entity2PersistenceDTO(entity);
	}

}