/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.cita.persistence;

import co.edu.uniandes.csw.Arquidalgos.cita.logic.dto.CitaDTO;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.Arquidalgos.cita.persistence.api.ICitaPersistence;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.ejb.LocalBean;
import utilidadesHTV.ConstantesYMetodos;
import utilidadesHTV.Tiempo;

@Default
@Stateless 
@LocalBean
public class CitaPersistence extends _CitaPersistence  implements ICitaPersistence {

    //TODO Falta verificar que si se agrega la primera cita reservada, se agregen las seguidas
    public List<CitaDTO> darCitasAnterioresOYa (Date fecha, Long idSede){
        
        List<CitaDTO> citas = darCitasHoy(idSede);
        List<CitaDTO> resp = new ArrayList<CitaDTO>();
        for (CitaDTO cita : citas) {
            
            if ( cita.isEspera() && (fecha.after(cita.getHoraIni())|| ConstantesYMetodos.citasMismoMinuto(fecha, cita.getHoraIni()))){
                
                resp.add(cita);
            }
            
        }
        
        return resp;
    }
    
    /**
     * Retorna todas las citas que se encuentran dentro del rango dado por parámetro
     * @param inicioRango
     * @param idSede
     * @return 
     */
    public List<CitaDTO> darCitasRango (Date inicioRango, Long idSede){
        
        List<CitaDTO> resp = new ArrayList<CitaDTO>();
        
        Date finRango = new Date (inicioRango.getTime()+ConstantesYMetodos.RANGO_RESERVAR_TURNO_MILISEGUNDOS);
        
        List <CitaDTO> citas = darCitasHoy(idSede);
       
        for (CitaDTO citaActual : citas) {
            
            if ( citaActual.getHoraIni().after(inicioRango) && citaActual.getHoraIni().before(finRango)){
                
                resp.add(citaActual);
            }
            
        }
        
        return resp;
    }
    
    
    
    /**
     * Retorna todas las citas que estan agendadas para hoy
     * @param idSede
     * @return 
     */
    public List <CitaDTO> darCitasHoy (Long idSede){
        
        List <CitaDTO> resp = new ArrayList<CitaDTO>();
               
        List<CitaDTO> citas = getCitas();
        
        for (CitaDTO cita : citas) {
            
            
            if ( cita.getSedecitaId().equals(idSede) && 
                    ConstantesYMetodos.citasMismoDia(Tiempo.getCurrentDate(), cita.getFechaCita())){
                                
                resp.add(cita);
            }
            
        }
        
        return resp;
    }
}