/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.entidad.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.Arquidalgos.entidad.logic.dto.EntidadDTO;
import co.edu.uniandes.csw.Arquidalgos.entidad.logic.api.IEntidadLogicService;
import co.edu.uniandes.csw.Arquidalgos.entidad.master.logic.api._IEntidadMasterLogicService;
import co.edu.uniandes.csw.Arquidalgos.entidad.master.logic.dto.EntidadMasterDTO;
import co.edu.uniandes.csw.Arquidalgos.sede.logic.api.ISedeLogicService;
import co.edu.uniandes.csw.Arquidalgos.sede.logic.dto.SedeDTO;
import javax.inject.Inject;


public abstract class _EntidadMasterMockLogicService implements _IEntidadMasterLogicService {

    protected static ArrayList<EntidadMasterDTO> entidadMasterDtosList = new ArrayList<EntidadMasterDTO>() ;
    @Inject
    protected ISedeLogicService sedePersistance;
    @Inject
    protected IEntidadLogicService entidadPersistance;

    public EntidadMasterDTO createMasterEntidad(EntidadMasterDTO entidad) {

        entidadPersistance.createEntidad(entidad.getEntidadEntity());
        for (SedeDTO dto : entidad.getCreatesedeEntidad()) {
            sedePersistance.createSede(dto);
        }
        entidadMasterDtosList.add(entidad);
        return entidad;
    }

    public EntidadMasterDTO getMasterEntidad(Long id) {
        for (EntidadMasterDTO entidadMasterDTO : entidadMasterDtosList) {
            if (entidadMasterDTO.getEntidadEntity().getId() == id) {
                return entidadMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterEntidad(Long id) {
        for (EntidadMasterDTO entidadMasterDTO : entidadMasterDtosList) {
            if (entidadMasterDTO.getEntidadEntity().getId() == id) {

                for (SedeDTO dto : entidadMasterDTO.getCreatesedeEntidad()) {
                    sedePersistance.deleteSede(dto.getId());
                }
                entidadPersistance.deleteEntidad(entidadMasterDTO.getId());
                entidadMasterDtosList.remove(entidadMasterDTO);
            }
        }

    }

    public void updateMasterEntidad(EntidadMasterDTO entidad) {

        // update Sede
        if (entidad.getUpdatesedeEntidad() != null) {
            for (SedeDTO dto : entidad.getUpdatesedeEntidad()) {
                sedePersistance.updateSede(dto);
            }
        }
        // persist new Sede
        if (entidad.getCreatesedeEntidad() != null) {
            for (SedeDTO dto : entidad.getCreatesedeEntidad()) {
                SedeDTO persistedSedeDTO = sedePersistance.createSede(dto);
                dto = persistedSedeDTO;
            }
        }
        // delete Sede
        if (entidad.getDeletesedeEntidad() != null) {
            for (SedeDTO dto : entidad.getDeletesedeEntidad()) {

                sedePersistance.deleteSede(dto.getId());
            }
        }
    }
}