/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.sede.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.Arquidalgos.sede.logic.dto.SedeDTO;
import co.edu.uniandes.csw.Arquidalgos.sede.persistence.api._ISedePersistence;
import co.edu.uniandes.csw.Arquidalgos.sede.persistence.converter.SedeConverter;
import co.edu.uniandes.csw.Arquidalgos.sede.persistence.entity.SedeEntity;

public abstract class _SedePersistence implements _ISedePersistence {

  	@PersistenceContext(unitName="HazTuVueltaPU")
 
	protected EntityManager entityManager;
	
	public SedeDTO createSede(SedeDTO sede) {
		SedeEntity entity=SedeConverter.persistenceDTO2Entity(sede);
		entityManager.persist(entity);
		return SedeConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<SedeDTO> getSedes() {
		Query q = entityManager.createQuery("select u from SedeEntity u");
		return SedeConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public SedeDTO getSede(Long id) {
		return SedeConverter.entity2PersistenceDTO(entityManager.find(SedeEntity.class, id));
	}

	public void deleteSede(Long id) {
		SedeEntity entity=entityManager.find(SedeEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateSede(SedeDTO detail) {
		SedeEntity entity=entityManager.merge(SedeConverter.persistenceDTO2Entity(detail));
		SedeConverter.entity2PersistenceDTO(entity);
	}

}