/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.usuario.master.persistence.entity;

import co.edu.uniandes.csw.Arquidalgos.cita.persistence.entity.CitaEntity;
import co.edu.uniandes.csw.Arquidalgos.usuario.persistence.entity.UsuarioEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(UsuariocitasUsEntityId.class)
@NamedQueries({
    @NamedQuery(name = "UsuariocitasUsEntity.getByMasterId", query = "SELECT  u FROM UsuariocitasUsEntity u WHERE u.usuarioId=:usuarioId"),
    @NamedQuery(name = "UsuariocitasUsEntity.deleteUsuariocitasUsEntity", query = "DELETE FROM UsuariocitasUsEntity u WHERE u.usuarioId=:usuarioId and  u.citasUsId=:citasUsId")
})
public class UsuariocitasUsEntity implements Serializable {

    @Id
    @Column(name = "usuarioId")
    private Long usuarioId;
    @Id
    @Column(name = "citasUsId")
    private Long citasUsId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "usuarioId", referencedColumnName = "id")
    @JoinFetch
    private CitaEntity usuarioIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "citasUsId", referencedColumnName = "id")
    @JoinFetch
    private CitaEntity citasUsIdEntity; 

    public UsuariocitasUsEntity() {
    }

    public UsuariocitasUsEntity(Long usuarioId, Long citasUsId) {
        this.usuarioId =usuarioId;
        this.citasUsId = citasUsId;
    }

    public Long getUsuarioId() {
        return usuarioId;
    }

    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }

    public Long getCitasUsId() {
        return citasUsId;
    }

    public void setCitasUsId(Long citasUsId) {
        this.citasUsId = citasUsId;
    }

    public CitaEntity getUsuarioIdEntity() {
        return usuarioIdEntity;
    }

    public void setUsuarioIdEntity(CitaEntity usuarioIdEntity) {
        this.usuarioIdEntity = usuarioIdEntity;
    }

    public CitaEntity getCitasUsIdEntity() {
        return citasUsIdEntity;
    }

    public void setCitasUsIdEntity(CitaEntity citasUsIdEntity) {
        this.citasUsIdEntity = citasUsIdEntity;
    }

}
