/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.turno.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.Arquidalgos.turno.logic.dto.TurnoDTO;
import co.edu.uniandes.csw.Arquidalgos.turno.persistence.api._ITurnoPersistence;
import co.edu.uniandes.csw.Arquidalgos.turno.persistence.converter.TurnoConverter;
import co.edu.uniandes.csw.Arquidalgos.turno.persistence.entity.TurnoEntity;

public abstract class _TurnoPersistence implements _ITurnoPersistence {

  	@PersistenceContext(unitName="HazTuVueltaPU")
 
	protected EntityManager entityManager;
	
	public TurnoDTO createTurno(TurnoDTO turno) {
		TurnoEntity entity=TurnoConverter.persistenceDTO2Entity(turno);
		entityManager.persist(entity);
		return TurnoConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<TurnoDTO> getTurnos() {
		Query q = entityManager.createQuery("select u from TurnoEntity u");
		return TurnoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public TurnoDTO getTurno(Long id) {
		return TurnoConverter.entity2PersistenceDTO(entityManager.find(TurnoEntity.class, id));
	}

	public void deleteTurno(Long id) {
		TurnoEntity entity=entityManager.find(TurnoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateTurno(TurnoDTO detail) {
		TurnoEntity entity=entityManager.merge(TurnoConverter.persistenceDTO2Entity(detail));
		TurnoConverter.entity2PersistenceDTO(entity);
	}

}