/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.entidad.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.Arquidalgos.entidad.logic.dto.EntidadDTO;
import co.edu.uniandes.csw.Arquidalgos.entidad.persistence.api._IEntidadPersistence;
import co.edu.uniandes.csw.Arquidalgos.entidad.persistence.converter.EntidadConverter;
import co.edu.uniandes.csw.Arquidalgos.entidad.persistence.entity.EntidadEntity;

public abstract class _EntidadPersistence implements _IEntidadPersistence {

  	@PersistenceContext(unitName="HazTuVueltaPU")
 
	protected EntityManager entityManager;
	
	public EntidadDTO createEntidad(EntidadDTO entidad) {
		EntidadEntity entity=EntidadConverter.persistenceDTO2Entity(entidad);
		entityManager.persist(entity);
		return EntidadConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<EntidadDTO> getEntidads() {
		Query q = entityManager.createQuery("select u from EntidadEntity u");
		return EntidadConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public EntidadDTO getEntidad(Long id) {
		return EntidadConverter.entity2PersistenceDTO(entityManager.find(EntidadEntity.class, id));
	}

	public void deleteEntidad(Long id) {
		EntidadEntity entity=entityManager.find(EntidadEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateEntidad(EntidadDTO detail) {
		EntidadEntity entity=entityManager.merge(EntidadConverter.persistenceDTO2Entity(detail));
		EntidadConverter.entity2PersistenceDTO(entity);
	}

}