/* ========================================================================
 * Copyright 2014 Arquidalgos
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Arquidalgos

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.Arquidalgos.usuario.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.Arquidalgos.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.Arquidalgos.usuario.logic.api.IUsuarioLogicService;
import co.edu.uniandes.csw.Arquidalgos.usuario.master.logic.api._IUsuarioMasterLogicService;
import co.edu.uniandes.csw.Arquidalgos.usuario.master.logic.dto.UsuarioMasterDTO;
import co.edu.uniandes.csw.Arquidalgos.turno.logic.api.ITurnoLogicService;
import co.edu.uniandes.csw.Arquidalgos.cita.logic.api.ICitaLogicService;
import co.edu.uniandes.csw.Arquidalgos.turno.logic.dto.TurnoDTO;
import co.edu.uniandes.csw.Arquidalgos.cita.logic.dto.CitaDTO;
import javax.inject.Inject;


public abstract class _UsuarioMasterMockLogicService implements _IUsuarioMasterLogicService {

    protected static ArrayList<UsuarioMasterDTO> usuarioMasterDtosList = new ArrayList<UsuarioMasterDTO>() ;
    @Inject
    protected ITurnoLogicService turnoPersistance;
    @Inject
    protected ICitaLogicService citaPersistance;
    @Inject
    protected IUsuarioLogicService usuarioPersistance;

    public UsuarioMasterDTO createMasterUsuario(UsuarioMasterDTO usuario) {

        usuarioPersistance.createUsuario(usuario.getUsuarioEntity());
        for (CitaDTO dto : usuario.getCreatecitasUs()) {
            citaPersistance.createCita(dto);
        }
        for (TurnoDTO dto : usuario.getCreateturnoUsuario()) {
            turnoPersistance.createTurno(dto);
        }
        usuarioMasterDtosList.add(usuario);
        return usuario;
    }

    public UsuarioMasterDTO getMasterUsuario(Long id) {
        for (UsuarioMasterDTO usuarioMasterDTO : usuarioMasterDtosList) {
            if (usuarioMasterDTO.getUsuarioEntity().getId() == id) {
                return usuarioMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterUsuario(Long id) {
        for (UsuarioMasterDTO usuarioMasterDTO : usuarioMasterDtosList) {
            if (usuarioMasterDTO.getUsuarioEntity().getId() == id) {

                for (CitaDTO dto : usuarioMasterDTO.getCreatecitasUs()) {
                    citaPersistance.deleteCita(dto.getId());
                }
                usuarioPersistance.deleteUsuario(usuarioMasterDTO.getId());
                usuarioMasterDtosList.remove(usuarioMasterDTO);
                for (TurnoDTO dto : usuarioMasterDTO.getCreateturnoUsuario()) {
                    turnoPersistance.deleteTurno(dto.getId());
                }
                usuarioPersistance.deleteUsuario(usuarioMasterDTO.getId());
                usuarioMasterDtosList.remove(usuarioMasterDTO);
            }
        }

    }

    public void updateMasterUsuario(UsuarioMasterDTO usuario) {

        // update Cita
        if (usuario.getUpdatecitasUs() != null) {
            for (CitaDTO dto : usuario.getUpdatecitasUs()) {
                citaPersistance.updateCita(dto);
            }
        }
        // persist new Cita
        if (usuario.getCreatecitasUs() != null) {
            for (CitaDTO dto : usuario.getCreatecitasUs()) {
                CitaDTO persistedCitaDTO = citaPersistance.createCita(dto);
                dto = persistedCitaDTO;
            }
        }
        // delete Cita
        if (usuario.getDeletecitasUs() != null) {
            for (CitaDTO dto : usuario.getDeletecitasUs()) {

                citaPersistance.deleteCita(dto.getId());
            }
        }
        // update Turno
        if (usuario.getUpdateturnoUsuario() != null) {
            for (TurnoDTO dto : usuario.getUpdateturnoUsuario()) {
                turnoPersistance.updateTurno(dto);
            }
        }
        // persist new Turno
        if (usuario.getCreateturnoUsuario() != null) {
            for (TurnoDTO dto : usuario.getCreateturnoUsuario()) {
                TurnoDTO persistedTurnoDTO = turnoPersistance.createTurno(dto);
                dto = persistedTurnoDTO;
            }
        }
        // delete Turno
        if (usuario.getDeleteturnoUsuario() != null) {
            for (TurnoDTO dto : usuario.getDeleteturnoUsuario()) {

                turnoPersistance.deleteTurno(dto.getId());
            }
        }
    }
}